### PR TITLE
Substitution Cipher, Last Men Standing

### PR DESCRIPTION
**Pull request by nikitashaw13**
Commonly used algorithm for a circular shift in Cryptography

### CODE REVIEW

**Comment by nikitashaw13** [comment]
Added another program: Last Men Standing

**Review by chanmol1999 — CHANGES_REQUESTED** [review]
Good Work!!
Try to squash the commits  into one

**Comment by chanmol1999** [comment]
@nikitashaw13 are you doing the changes?

**Comment by nikitashaw13** [comment]
Yes

**Comment by nikitashaw13** [comment]
squashed the commits of last men standing program. Please review them

**Review by chanmol1999 — APPROVED** [review]

**Pull request merged**
