### PR TITLE
Added program to permute over a string

### PR DESCRIPTION
**Pull request by sanket0x**

### CODE REVIEW

**Review by abhishekchopra13 — CHANGES_REQUESTED** [review]
Just change name of the algorithm to a more specific one.

**Review by sanket0x — COMMENTED** [review]
changed the algorithm name to "string_permutation" as it prints all permutations over a string

**Comment by sanket0x** [comment]
also added a code for insertion and traversal on BST and updated readme

**Comment by Bhavnaharitsa** [comment]
Resolve conflicts

**Comment by sanket0x** [comment]
Resolved all the conflicts

**Comment by chanmol1999** [comment]
Resolve the conflicts @San-B-09

**Pull request closed without merging**
