### PR TITLE
Finding NextLarger is added in Stack

### PR DESCRIPTION
**Pull request by vishal-bhola**
Algorithm to find  Next Larger element in array is implemented using stack.

### CODE REVIEW

**Comment by VersatileVishal** [comment]
@Bhavnaharitsa please review this PR

**Comment by vishal-bhola** [comment]
@Bhavnaharitsa  Please review my PR #85

**Comment by Bhavnaharitsa** [comment]
You have exceeded the limit of 2 prs. 
So this will not be a valid contribution

**Comment by vishal-bhola** [comment]
But it's not mention anywhere that only 2 contribution are valid

**Comment by Bhavnaharitsa** [comment]
I mean you can contribute but points wont be added

**Comment by vishal-bhola** [comment]
So, you mean that I can't contribute on any of the topics or only this
particular topic?

**Comment by vishal-bhola** [comment]
Ok, so kindly merge this PR also.

**Review by chanmol1999 — APPROVED** [review]

**Comment by chanmol1999** [comment]
Thanks.
But you wont get points for this

**Pull request merged**
