### PR TITLE
Substitution_Cipher link failing resolved

### PR DESCRIPTION
**Pull request by ashiscs**

### CODE REVIEW

**Comment by ashiscs** [comment]
@Bhavnaharitsa please review?

**Comment by Bhavnaharitsa** [comment]
shove these changes in the previous pr..no need to make a new pr for this

**Comment by ashiscs** [comment]
@Bhavnaharitsa still the link is failing, that's why I created a new pr
You can check it?

**Comment by Bhavnaharitsa** [comment]
Okay I am asking you to make the changes in the previous pr

**Pull request closed without merging**
