### PR TITLE
Tree Sort & Infix Converter

### PR DESCRIPTION
**Pull request by adiXcodr**
1. Binary Search Tree Sort (C++)
2. Infix to Prefix Converter (C++)
3. Infix to Postfix Converter (C++)

Kindly ignore the previous commits, they have been rectified in the latest pull request.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
Why are these too many pull requests on a single issue?

**Comment by adiXcodr** [comment]
> Why are these too many pull requests on a single issue?

I had closed the previous pull requests. These are just the previous commits in the branch ehich have been overwritten by the latest change which satisfies the requirements put forward by you.

**Comment by Bhavnaharitsa** [comment]
Yeah but you could have commited the changes. Why new pull requests everytime?

**Comment by adiXcodr** [comment]
> Yeah but you could have commited the changes. Why new pull requests everytime?

I apologise. I thought one needed to close the pull request first. Thanks for the clarification.

**Pull request merged**
