### PR TITLE
Tree Sort, Infix2PostfixPrefixValue

### PR DESCRIPTION
**Pull request by adiXcodr**
Tree Sort-
Sorting given values by adding them in a Binary Search Tree and then storing the Inorder Traversal to get sorted values. (C++)

Infix Evaluation-
Converts given Infix expression to Prefix, Postfix and calculates the value of the same. (C++)

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
Could you make separate algorithms for infix, prefix and postfix

**Comment by adiXcodr** [comment]
> Could you make separate algorithms for infix, prefix and postfix

Sure. I'll do it and create a new PR. Do we need an infix to postfix/prefix converter or an expression evaluator for all the three forms?

**Comment by Bhavnaharitsa** [comment]
Sure, you can close this now.

**Comment by adiXcodr** [comment]
> Sure, you can close this now.

As I asked before, Do we need an infix to postfix/prefix converter or an expression evaluator for all the three forms? Thanks.

**Comment by Bhavnaharitsa** [comment]
convertor for now

**Comment by adiXcodr** [comment]
> convertor for now

Sure.

**Pull request closed without merging**
