### PR TITLE
Longest Common Subsequence Algo Added

### PR DESCRIPTION
**Pull request by saumya1singh**

### CODE REVIEW

**Review by abhishekchopra13 — CHANGES_REQUESTED** [review]
Please provide the implementation only in a cpp file with apt parameters.

**Review by abhishekchopra13 — CHANGES_REQUESTED** [review]
Algorithm is fine just remove the process it is not needed.

**Comment by saumya1singh** [comment]
@abhishekchopra13  I have made the required changes in PR #14

**Comment by Bhavnaharitsa** [comment]
@SaumyaSingh1 Closing this as the changes are in other pr

**Pull request closed without merging**
