### PR TITLE
 knapsack algo added

### PR DESCRIPTION
**Pull request by saumya1singh**

### CODE REVIEW

**Review by shashwat211 — CHANGES_REQUESTED** [review]
You need to make a folder with your Algorithm name and within it put your algoritm's description as well as your program.

**Comment by saumya1singh** [comment]
Sure @shashwat211

**Comment by Bhavnaharitsa** [comment]
@SaumyaSingh1 Are the changes done?

**Comment by chanmol1999** [comment]
No Response going to close

**Pull request closed without merging**
