### PR TITLE
Added Rabin Karp and Heap Sort algorithm

### PR DESCRIPTION
**Pull request by sarthakeddy**
Added rabin karp algorithm and count of different substrings of given string in String Hashing folder, and heap sort algorithm in sorting algorithms folder

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
Please squash your commits and resolve conflicts

**Comment by Bhavnaharitsa** [comment]
Please squash your commits and resolve conflicts

**Comment by Bhavnaharitsa** [comment]
Please squash your commits and resolve conflicts

**Comment by sarthakeddy** [comment]
Can you please elaborate what exactly I have to do, actually I am a newbie.

**Pull request merged**
