### PR TITLE
updated readme.md

### PR DESCRIPTION
**Pull request by ashiscs**

### CODE REVIEW

**Comment by ashiscs** [comment]
Where i can see my score?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/21/19,
02:49:06 PM

**Comment by Bhavnaharitsa** [comment]
leaderboard

**Comment by ashiscs** [comment]
Can you provide the link, i am not able to see it?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/21/19,
02:55:07 PM

**Comment by ashiscs** [comment]
Hey, my name is not showing on the leaderboard?




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/22/19,
04:49:59 AM

**Pull request merged**
