### PR TITLE
 0-1 Knapsack Algorithm

### PR DESCRIPTION
**Pull request by saumya1singh**
Complete description of 0-1 Knapsack Problem .

### CODE REVIEW

**Comment by saumya1singh** [comment]
@abhishekchopra13  Have a look at my PR . Do i need to add something else ?

**Review by shashwat211 — CHANGES_REQUESTED** [review]
You need to add a folder with the name of your algorithm and within it, you must write a documentation of your code along with your program.

**Comment by Bhavnaharitsa** [comment]
@SaumyaSingh1 Are you done?

**Comment by chanmol1999** [comment]
No Response going to close

**Pull request closed without merging**
